### ISSUE TITLE
Function to store strings to the google sheets

### ISSUE THREAD

**Issue by franky72003** [Killkase42/cpt-projectfx#3]
Hey Nick, can you make a function which stores strings to the google sheets. right now I just need a way to store the username and password.

**Comment by Killkase42** [comment]
Done, I rewrote the `SheetsAPI` file and made simple methods for reading a specified area and writing to two columns in one row, which are both already in the main method. I will comment it later and add more features such as checking to see if there is a certain string on the sheet.  I also made a new spreadsheet that everyone can upload to and added you.
